// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sgl_cox_fit_cpp
Rcpp::List sgl_cox_fit_cpp(const arma::mat& X, const arma::mat& time, const arma::mat& status, const arma::mat& group_index, const arma::mat& group_weight, const arma::mat& initial_beta, const double lambda, const double alpha, const double step_size, const int max_iter, const double tol);
RcppExport SEXP _SGL2_sgl_cox_fit_cpp(SEXP XSEXP, SEXP timeSEXP, SEXP statusSEXP, SEXP group_indexSEXP, SEXP group_weightSEXP, SEXP initial_betaSEXP, SEXP lambdaSEXP, SEXP alphaSEXP, SEXP step_sizeSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type status(statusSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type group_index(group_indexSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type group_weight(group_weightSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type initial_beta(initial_betaSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type step_size(step_sizeSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(sgl_cox_fit_cpp(X, time, status, group_index, group_weight, initial_beta, lambda, alpha, step_size, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// sgl_group_l2_norm_cpp
double sgl_group_l2_norm_cpp(const arma::mat& z);
RcppExport SEXP _SGL2_sgl_group_l2_norm_cpp(SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(sgl_group_l2_norm_cpp(z));
    return rcpp_result_gen;
END_RCPP
}
// sgl_group_layout_cpp
Rcpp::List sgl_group_layout_cpp(const arma::mat& group_index);
RcppExport SEXP _SGL2_sgl_group_layout_cpp(SEXP group_indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type group_index(group_indexSEXP);
    rcpp_result_gen = Rcpp::wrap(sgl_group_layout_cpp(group_index));
    return rcpp_result_gen;
END_RCPP
}
// sgl_sparse_group_prox_groups_cpp
arma::mat sgl_sparse_group_prox_groups_cpp(arma::mat beta, const arma::mat& group_index, const arma::mat& group_weight, const double lambda_l1, const double lambda_group);
RcppExport SEXP _SGL2_sgl_sparse_group_prox_groups_cpp(SEXP betaSEXP, SEXP group_indexSEXP, SEXP group_weightSEXP, SEXP lambda_l1SEXP, SEXP lambda_groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type group_index(group_indexSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type group_weight(group_weightSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda_l1(lambda_l1SEXP);
    Rcpp::traits::input_parameter< const double >::type lambda_group(lambda_groupSEXP);
    rcpp_result_gen = Rcpp::wrap(sgl_sparse_group_prox_groups_cpp(beta, group_index, group_weight, lambda_l1, lambda_group));
    return rcpp_result_gen;
END_RCPP
}
// sgl_sparse_group_prox_groups_cached_cpp
arma::mat sgl_sparse_group_prox_groups_cached_cpp(arma::mat beta, const arma::mat& member_order, const arma::mat& offsets, const arma::mat& group_weight, const double lambda_l1, const double lambda_group);
RcppExport SEXP _SGL2_sgl_sparse_group_prox_groups_cached_cpp(SEXP betaSEXP, SEXP member_orderSEXP, SEXP offsetsSEXP, SEXP group_weightSEXP, SEXP lambda_l1SEXP, SEXP lambda_groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type member_order(member_orderSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type offsets(offsetsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type group_weight(group_weightSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda_l1(lambda_l1SEXP);
    Rcpp::traits::input_parameter< const double >::type lambda_group(lambda_groupSEXP);
    rcpp_result_gen = Rcpp::wrap(sgl_sparse_group_prox_groups_cached_cpp(beta, member_order, offsets, group_weight, lambda_l1, lambda_group));
    return rcpp_result_gen;
END_RCPP
}
// sgl_sparse_group_prox_update_eta_cached_cpp
Rcpp::List sgl_sparse_group_prox_update_eta_cached_cpp(arma::mat beta, arma::mat eta, const arma::mat& X, const arma::mat& member_order, const arma::mat& offsets, const arma::mat& group_weight, const double lambda_l1, const double lambda_group);
RcppExport SEXP _SGL2_sgl_sparse_group_prox_update_eta_cached_cpp(SEXP betaSEXP, SEXP etaSEXP, SEXP XSEXP, SEXP member_orderSEXP, SEXP offsetsSEXP, SEXP group_weightSEXP, SEXP lambda_l1SEXP, SEXP lambda_groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type member_order(member_orderSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type offsets(offsetsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type group_weight(group_weightSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda_l1(lambda_l1SEXP);
    Rcpp::traits::input_parameter< const double >::type lambda_group(lambda_groupSEXP);
    rcpp_result_gen = Rcpp::wrap(sgl_sparse_group_prox_update_eta_cached_cpp(beta, eta, X, member_order, offsets, group_weight, lambda_l1, lambda_group));
    return rcpp_result_gen;
END_RCPP
}
// sgl_linear_intercept_gradient_cpp
double sgl_linear_intercept_gradient_cpp(const arma::mat& eta, const arma::mat& y);
RcppExport SEXP _SGL2_sgl_linear_intercept_gradient_cpp(SEXP etaSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(sgl_linear_intercept_gradient_cpp(eta, y));
    return rcpp_result_gen;
END_RCPP
}
// sgl_logistic_intercept_gradient_cpp
double sgl_logistic_intercept_gradient_cpp(const arma::mat& eta, const arma::mat& y);
RcppExport SEXP _SGL2_sgl_logistic_intercept_gradient_cpp(SEXP etaSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(sgl_logistic_intercept_gradient_cpp(eta, y));
    return rcpp_result_gen;
END_RCPP
}
// sgl_logistic_intercept_hessian_cpp
double sgl_logistic_intercept_hessian_cpp(const arma::mat& eta);
RcppExport SEXP _SGL2_sgl_logistic_intercept_hessian_cpp(SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(sgl_logistic_intercept_hessian_cpp(eta));
    return rcpp_result_gen;
END_RCPP
}
// sgl_update_intercept_eta_cpp
Rcpp::List sgl_update_intercept_eta_cpp(arma::mat intercept, arma::mat eta, const double delta_intercept);
RcppExport SEXP _SGL2_sgl_update_intercept_eta_cpp(SEXP interceptSEXP, SEXP etaSEXP, SEXP delta_interceptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const double >::type delta_intercept(delta_interceptSEXP);
    rcpp_result_gen = Rcpp::wrap(sgl_update_intercept_eta_cpp(intercept, eta, delta_intercept));
    return rcpp_result_gen;
END_RCPP
}
// sgl_update_eta_cpp
arma::mat sgl_update_eta_cpp(const arma::mat& X, arma::mat eta, const arma::mat& delta_beta);
RcppExport SEXP _SGL2_sgl_update_eta_cpp(SEXP XSEXP, SEXP etaSEXP, SEXP delta_betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type delta_beta(delta_betaSEXP);
    rcpp_result_gen = Rcpp::wrap(sgl_update_eta_cpp(X, eta, delta_beta));
    return rcpp_result_gen;
END_RCPP
}
// sgl_update_eta_group_cpp
arma::mat sgl_update_eta_group_cpp(const arma::mat& X, arma::mat eta, const arma::mat& delta_beta, const int first_col, const int last_col);
RcppExport SEXP _SGL2_sgl_update_eta_group_cpp(SEXP XSEXP, SEXP etaSEXP, SEXP delta_betaSEXP, SEXP first_colSEXP, SEXP last_colSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type delta_beta(delta_betaSEXP);
    Rcpp::traits::input_parameter< const int >::type first_col(first_colSEXP);
    Rcpp::traits::input_parameter< const int >::type last_col(last_colSEXP);
    rcpp_result_gen = Rcpp::wrap(sgl_update_eta_group_cpp(X, eta, delta_beta, first_col, last_col));
    return rcpp_result_gen;
END_RCPP
}
// sgl_gradient_xt_residual_cpp
arma::mat sgl_gradient_xt_residual_cpp(const arma::mat& X, const arma::mat& residual);
RcppExport SEXP _SGL2_sgl_gradient_xt_residual_cpp(SEXP XSEXP, SEXP residualSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type residual(residualSEXP);
    rcpp_result_gen = Rcpp::wrap(sgl_gradient_xt_residual_cpp(X, residual));
    return rcpp_result_gen;
END_RCPP
}
// sgl_gradient_group_xt_residual_cpp
arma::mat sgl_gradient_group_xt_residual_cpp(const arma::mat& X, const arma::mat& residual, const int first_col, const int last_col);
RcppExport SEXP _SGL2_sgl_gradient_group_xt_residual_cpp(SEXP XSEXP, SEXP residualSEXP, SEXP first_colSEXP, SEXP last_colSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type residual(residualSEXP);
    Rcpp::traits::input_parameter< const int >::type first_col(first_colSEXP);
    Rcpp::traits::input_parameter< const int >::type last_col(last_colSEXP);
    rcpp_result_gen = Rcpp::wrap(sgl_gradient_group_xt_residual_cpp(X, residual, first_col, last_col));
    return rcpp_result_gen;
END_RCPP
}
// sgl_linear_gradient_cpp
arma::mat sgl_linear_gradient_cpp(const arma::mat& X, const arma::mat& eta, const arma::mat& y);
RcppExport SEXP _SGL2_sgl_linear_gradient_cpp(SEXP XSEXP, SEXP etaSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(sgl_linear_gradient_cpp(X, eta, y));
    return rcpp_result_gen;
END_RCPP
}
// sgl_linear_squared_loss_cpp
double sgl_linear_squared_loss_cpp(const arma::mat& eta, const arma::mat& y);
RcppExport SEXP _SGL2_sgl_linear_squared_loss_cpp(SEXP etaSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(sgl_linear_squared_loss_cpp(eta, y));
    return rcpp_result_gen;
END_RCPP
}
// sgl_initialize_linear_predictor_cpp
arma::mat sgl_initialize_linear_predictor_cpp(const arma::mat& X, const arma::mat& beta, const arma::mat& intercept);
RcppExport SEXP _SGL2_sgl_initialize_linear_predictor_cpp(SEXP XSEXP, SEXP betaSEXP, SEXP interceptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type intercept(interceptSEXP);
    rcpp_result_gen = Rcpp::wrap(sgl_initialize_linear_predictor_cpp(X, beta, intercept));
    return rcpp_result_gen;
END_RCPP
}
// sgl_update_linear_predictor_state_cpp
arma::mat sgl_update_linear_predictor_state_cpp(arma::mat eta, const arma::mat& X, const arma::mat& beta_old, const arma::mat& beta_new, const arma::mat& intercept_old, const arma::mat& intercept_new);
RcppExport SEXP _SGL2_sgl_update_linear_predictor_state_cpp(SEXP etaSEXP, SEXP XSEXP, SEXP beta_oldSEXP, SEXP beta_newSEXP, SEXP intercept_oldSEXP, SEXP intercept_newSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta_old(beta_oldSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta_new(beta_newSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type intercept_old(intercept_oldSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type intercept_new(intercept_newSEXP);
    rcpp_result_gen = Rcpp::wrap(sgl_update_linear_predictor_state_cpp(eta, X, beta_old, beta_new, intercept_old, intercept_new));
    return rcpp_result_gen;
END_RCPP
}
// sgl_linear_fit_cpp
Rcpp::List sgl_linear_fit_cpp(const arma::mat& X, const arma::mat& y, const arma::mat& group_index, const arma::mat& group_weight, const arma::mat& initial_beta, const arma::mat& initial_intercept, const double lambda, const double alpha, const double step_size, const int max_iter, const double tol, const bool fit_intercept);
RcppExport SEXP _SGL2_sgl_linear_fit_cpp(SEXP XSEXP, SEXP ySEXP, SEXP group_indexSEXP, SEXP group_weightSEXP, SEXP initial_betaSEXP, SEXP initial_interceptSEXP, SEXP lambdaSEXP, SEXP alphaSEXP, SEXP step_sizeSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP fit_interceptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type group_index(group_indexSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type group_weight(group_weightSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type initial_beta(initial_betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type initial_intercept(initial_interceptSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type step_size(step_sizeSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const bool >::type fit_intercept(fit_interceptSEXP);
    rcpp_result_gen = Rcpp::wrap(sgl_linear_fit_cpp(X, y, group_index, group_weight, initial_beta, initial_intercept, lambda, alpha, step_size, max_iter, tol, fit_intercept));
    return rcpp_result_gen;
END_RCPP
}
// sgl_logistic_fit_cpp
Rcpp::List sgl_logistic_fit_cpp(const arma::mat& X, const arma::mat& y, const arma::mat& group_index, const arma::mat& group_weight, const arma::mat& initial_beta, const arma::mat& initial_intercept, const double lambda, const double alpha, const double step_size, const int max_iter, const double tol, const bool fit_intercept);
RcppExport SEXP _SGL2_sgl_logistic_fit_cpp(SEXP XSEXP, SEXP ySEXP, SEXP group_indexSEXP, SEXP group_weightSEXP, SEXP initial_betaSEXP, SEXP initial_interceptSEXP, SEXP lambdaSEXP, SEXP alphaSEXP, SEXP step_sizeSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP fit_interceptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type group_index(group_indexSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type group_weight(group_weightSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type initial_beta(initial_betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type initial_intercept(initial_interceptSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type step_size(step_sizeSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const bool >::type fit_intercept(fit_interceptSEXP);
    rcpp_result_gen = Rcpp::wrap(sgl_logistic_fit_cpp(X, y, group_index, group_weight, initial_beta, initial_intercept, lambda, alpha, step_size, max_iter, tol, fit_intercept));
    return rcpp_result_gen;
END_RCPP
}
// sgl_logistic_probability_cpp
arma::mat sgl_logistic_probability_cpp(const arma::mat& eta);
RcppExport SEXP _SGL2_sgl_logistic_probability_cpp(SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(sgl_logistic_probability_cpp(eta));
    return rcpp_result_gen;
END_RCPP
}
// sgl_logistic_nll_gradient_cpp
arma::mat sgl_logistic_nll_gradient_cpp(const arma::mat& X, const arma::mat& eta, const arma::mat& y);
RcppExport SEXP _SGL2_sgl_logistic_nll_gradient_cpp(SEXP XSEXP, SEXP etaSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(sgl_logistic_nll_gradient_cpp(X, eta, y));
    return rcpp_result_gen;
END_RCPP
}
// sgl_logistic_nll_cpp
double sgl_logistic_nll_cpp(const arma::mat& eta, const arma::mat& y);
RcppExport SEXP _SGL2_sgl_logistic_nll_cpp(SEXP etaSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(sgl_logistic_nll_cpp(eta, y));
    return rcpp_result_gen;
END_RCPP
}
// sgl_sparse_group_prox_cpp
arma::mat sgl_sparse_group_prox_cpp(arma::mat z, const double lambda_l1, const double lambda_group, const double group_weight);
RcppExport SEXP _SGL2_sgl_sparse_group_prox_cpp(SEXP zSEXP, SEXP lambda_l1SEXP, SEXP lambda_groupSEXP, SEXP group_weightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type z(zSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda_l1(lambda_l1SEXP);
    Rcpp::traits::input_parameter< const double >::type lambda_group(lambda_groupSEXP);
    Rcpp::traits::input_parameter< const double >::type group_weight(group_weightSEXP);
    rcpp_result_gen = Rcpp::wrap(sgl_sparse_group_prox_cpp(z, lambda_l1, lambda_group, group_weight));
    return rcpp_result_gen;
END_RCPP
}
// sgl_prox_test
arma::vec sgl_prox_test(arma::vec z, const double lambda_l1, const double lambda_group, const double group_weight);
RcppExport SEXP _SGL2_sgl_prox_test(SEXP zSEXP, SEXP lambda_l1SEXP, SEXP lambda_groupSEXP, SEXP group_weightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type z(zSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda_l1(lambda_l1SEXP);
    Rcpp::traits::input_parameter< const double >::type lambda_group(lambda_groupSEXP);
    Rcpp::traits::input_parameter< const double >::type group_weight(group_weightSEXP);
    rcpp_result_gen = Rcpp::wrap(sgl_prox_test(z, lambda_l1, lambda_group, group_weight));
    return rcpp_result_gen;
END_RCPP
}

RcppExport void Cox(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *);
RcppExport void coxSolver(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *);
RcppExport void linNest(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *);
RcppExport void logitNest(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *);

static const R_CallMethodDef CallEntries[] = {
    {"_SGL2_sgl_cox_fit_cpp", (DL_FUNC) &_SGL2_sgl_cox_fit_cpp, 11},
    {"_SGL2_sgl_group_l2_norm_cpp", (DL_FUNC) &_SGL2_sgl_group_l2_norm_cpp, 1},
    {"_SGL2_sgl_group_layout_cpp", (DL_FUNC) &_SGL2_sgl_group_layout_cpp, 1},
    {"_SGL2_sgl_sparse_group_prox_groups_cpp", (DL_FUNC) &_SGL2_sgl_sparse_group_prox_groups_cpp, 5},
    {"_SGL2_sgl_sparse_group_prox_groups_cached_cpp", (DL_FUNC) &_SGL2_sgl_sparse_group_prox_groups_cached_cpp, 6},
    {"_SGL2_sgl_sparse_group_prox_update_eta_cached_cpp", (DL_FUNC) &_SGL2_sgl_sparse_group_prox_update_eta_cached_cpp, 8},
    {"_SGL2_sgl_linear_intercept_gradient_cpp", (DL_FUNC) &_SGL2_sgl_linear_intercept_gradient_cpp, 2},
    {"_SGL2_sgl_logistic_intercept_gradient_cpp", (DL_FUNC) &_SGL2_sgl_logistic_intercept_gradient_cpp, 2},
    {"_SGL2_sgl_logistic_intercept_hessian_cpp", (DL_FUNC) &_SGL2_sgl_logistic_intercept_hessian_cpp, 1},
    {"_SGL2_sgl_update_intercept_eta_cpp", (DL_FUNC) &_SGL2_sgl_update_intercept_eta_cpp, 3},
    {"_SGL2_sgl_update_eta_cpp", (DL_FUNC) &_SGL2_sgl_update_eta_cpp, 3},
    {"_SGL2_sgl_update_eta_group_cpp", (DL_FUNC) &_SGL2_sgl_update_eta_group_cpp, 5},
    {"_SGL2_sgl_gradient_xt_residual_cpp", (DL_FUNC) &_SGL2_sgl_gradient_xt_residual_cpp, 2},
    {"_SGL2_sgl_gradient_group_xt_residual_cpp", (DL_FUNC) &_SGL2_sgl_gradient_group_xt_residual_cpp, 4},
    {"_SGL2_sgl_linear_gradient_cpp", (DL_FUNC) &_SGL2_sgl_linear_gradient_cpp, 3},
    {"_SGL2_sgl_linear_squared_loss_cpp", (DL_FUNC) &_SGL2_sgl_linear_squared_loss_cpp, 2},
    {"_SGL2_sgl_initialize_linear_predictor_cpp", (DL_FUNC) &_SGL2_sgl_initialize_linear_predictor_cpp, 3},
    {"_SGL2_sgl_update_linear_predictor_state_cpp", (DL_FUNC) &_SGL2_sgl_update_linear_predictor_state_cpp, 6},
    {"_SGL2_sgl_linear_fit_cpp", (DL_FUNC) &_SGL2_sgl_linear_fit_cpp, 12},
    {"_SGL2_sgl_logistic_fit_cpp", (DL_FUNC) &_SGL2_sgl_logistic_fit_cpp, 12},
    {"_SGL2_sgl_logistic_probability_cpp", (DL_FUNC) &_SGL2_sgl_logistic_probability_cpp, 1},
    {"_SGL2_sgl_logistic_nll_gradient_cpp", (DL_FUNC) &_SGL2_sgl_logistic_nll_gradient_cpp, 3},
    {"_SGL2_sgl_logistic_nll_cpp", (DL_FUNC) &_SGL2_sgl_logistic_nll_cpp, 2},
    {"_SGL2_sgl_sparse_group_prox_cpp", (DL_FUNC) &_SGL2_sgl_sparse_group_prox_cpp, 4},
    {"_SGL2_sgl_prox_test", (DL_FUNC) &_SGL2_sgl_prox_test, 4},
    {"Cox",       (DL_FUNC) &Cox,       11},
    {"coxSolver", (DL_FUNC) &coxSolver, 25},
    {"linNest",   (DL_FUNC) &linNest,   20},
    {"logitNest", (DL_FUNC) &logitNest, 20},
    {NULL, NULL, 0}
};

RcppExport void R_init_SGL2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
