# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sgl_center_scale_cpp <- function(X, standardize = TRUE) {
    .Call(`_SGL2_sgl_center_scale_cpp`, X, standardize)
}

sgl_lambda_max_from_gradient_cpp <- function(gradient, group_index, group_weight, alpha) {
    .Call(`_SGL2_sgl_lambda_max_from_gradient_cpp`, gradient, group_index, group_weight, alpha)
}

sgl_make_lambda_path_cpp <- function(lambda_input, lambda_max, n_lambda, min_frac, lambda_decay) {
    .Call(`_SGL2_sgl_make_lambda_path_cpp`, lambda_input, lambda_max, n_lambda, min_frac, lambda_decay)
}

sgl_parse_cox_response_cpp <- function(response) {
    .Call(`_SGL2_sgl_parse_cox_response_cpp`, response)
}

sgl_cox_zero_gradient_cpp <- function(X, time, status) {
    .Call(`_SGL2_sgl_cox_zero_gradient_cpp`, X, time, status)
}

sgl_cox_fit_cpp <- function(X, time, status, group_index, group_weight, initial_beta, lambda, alpha, step_size, max_iter, tol) {
    .Call(`_SGL2_sgl_cox_fit_cpp`, X, time, status, group_index, group_weight, initial_beta, lambda, alpha, step_size, max_iter, tol)
}

sgl_cox_path_cpp <- function(X, time, status, group_index, group_weight, initial_beta, lambda_path, alpha, step_size, max_iter, tol) {
    .Call(`_SGL2_sgl_cox_path_cpp`, X, time, status, group_index, group_weight, initial_beta, lambda_path, alpha, step_size, max_iter, tol)
}

sgl_group_l2_norm_cpp <- function(z) {
    .Call(`_SGL2_sgl_group_l2_norm_cpp`, z)
}

sgl_group_layout_cpp <- function(group_index) {
    .Call(`_SGL2_sgl_group_layout_cpp`, group_index)
}

sgl_sparse_group_prox_groups_cpp <- function(beta, group_index, group_weight, lambda_l1, lambda_group) {
    .Call(`_SGL2_sgl_sparse_group_prox_groups_cpp`, beta, group_index, group_weight, lambda_l1, lambda_group)
}

sgl_sparse_group_prox_groups_cached_cpp <- function(beta, member_order, offsets, group_weight, lambda_l1, lambda_group) {
    .Call(`_SGL2_sgl_sparse_group_prox_groups_cached_cpp`, beta, member_order, offsets, group_weight, lambda_l1, lambda_group)
}

sgl_sparse_group_prox_update_eta_cached_cpp <- function(beta, eta, X, member_order, offsets, group_weight, lambda_l1, lambda_group) {
    .Call(`_SGL2_sgl_sparse_group_prox_update_eta_cached_cpp`, beta, eta, X, member_order, offsets, group_weight, lambda_l1, lambda_group)
}

sgl_linear_intercept_gradient_cpp <- function(eta, y) {
    .Call(`_SGL2_sgl_linear_intercept_gradient_cpp`, eta, y)
}

sgl_logistic_intercept_gradient_cpp <- function(eta, y) {
    .Call(`_SGL2_sgl_logistic_intercept_gradient_cpp`, eta, y)
}

sgl_logistic_intercept_hessian_cpp <- function(eta) {
    .Call(`_SGL2_sgl_logistic_intercept_hessian_cpp`, eta)
}

sgl_update_intercept_eta_cpp <- function(intercept, eta, delta_intercept) {
    .Call(`_SGL2_sgl_update_intercept_eta_cpp`, intercept, eta, delta_intercept)
}

sgl_update_eta_cpp <- function(X, eta, delta_beta) {
    .Call(`_SGL2_sgl_update_eta_cpp`, X, eta, delta_beta)
}

sgl_update_eta_group_cpp <- function(X, eta, delta_beta, first_col, last_col) {
    .Call(`_SGL2_sgl_update_eta_group_cpp`, X, eta, delta_beta, first_col, last_col)
}

sgl_gradient_xt_residual_cpp <- function(X, residual) {
    .Call(`_SGL2_sgl_gradient_xt_residual_cpp`, X, residual)
}

sgl_gradient_group_xt_residual_cpp <- function(X, residual, first_col, last_col) {
    .Call(`_SGL2_sgl_gradient_group_xt_residual_cpp`, X, residual, first_col, last_col)
}

sgl_linear_gradient_cpp <- function(X, eta, y) {
    .Call(`_SGL2_sgl_linear_gradient_cpp`, X, eta, y)
}

sgl_linear_squared_loss_cpp <- function(eta, y) {
    .Call(`_SGL2_sgl_linear_squared_loss_cpp`, eta, y)
}

sgl_initialize_linear_predictor_cpp <- function(X, beta, intercept) {
    .Call(`_SGL2_sgl_initialize_linear_predictor_cpp`, X, beta, intercept)
}

sgl_update_linear_predictor_state_cpp <- function(eta, X, beta_old, beta_new, intercept_old, intercept_new) {
    .Call(`_SGL2_sgl_update_linear_predictor_state_cpp`, eta, X, beta_old, beta_new, intercept_old, intercept_new)
}

sgl_linear_fit_cpp <- function(X, y, group_index, group_weight, initial_beta, initial_intercept, lambda, alpha, step_size, max_iter, tol, fit_intercept) {
    .Call(`_SGL2_sgl_linear_fit_cpp`, X, y, group_index, group_weight, initial_beta, initial_intercept, lambda, alpha, step_size, max_iter, tol, fit_intercept)
}

sgl_logistic_fit_cpp <- function(X, y, group_index, group_weight, initial_beta, initial_intercept, lambda, alpha, step_size, max_iter, tol, fit_intercept) {
    .Call(`_SGL2_sgl_logistic_fit_cpp`, X, y, group_index, group_weight, initial_beta, initial_intercept, lambda, alpha, step_size, max_iter, tol, fit_intercept)
}

sgl_logistic_path_cpp <- function(X, y, group_index, group_weight, initial_beta, initial_intercept, lambda_path, alpha, step_size, max_iter, tol, fit_intercept) {
    .Call(`_SGL2_sgl_logistic_path_cpp`, X, y, group_index, group_weight, initial_beta, initial_intercept, lambda_path, alpha, step_size, max_iter, tol, fit_intercept)
}

sgl_logistic_probability_cpp <- function(eta) {
    .Call(`_SGL2_sgl_logistic_probability_cpp`, eta)
}

sgl_logistic_nll_gradient_cpp <- function(X, eta, y) {
    .Call(`_SGL2_sgl_logistic_nll_gradient_cpp`, X, eta, y)
}

sgl_logistic_nll_cpp <- function(eta, y) {
    .Call(`_SGL2_sgl_logistic_nll_cpp`, eta, y)
}

sgl_sparse_group_prox_cpp <- function(z, lambda_l1, lambda_group, group_weight = 1.0) {
    .Call(`_SGL2_sgl_sparse_group_prox_cpp`, z, lambda_l1, lambda_group, group_weight)
}

sgl_prox_test <- function(z, lambda_l1, lambda_group, group_weight = 1.0) {
    .Call(`_SGL2_sgl_prox_test`, z, lambda_l1, lambda_group, group_weight)
}

